/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.service.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum AvroOrderStatus implements org.apache.avro.generic.GenericEnumSymbol<AvroOrderStatus> {
  NEW, ACCEPT, REJECT, CONFIRMATION, ROLLBACK  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AvroOrderStatus\",\"namespace\":\"com.service.avro.model\",\"symbols\":[\"NEW\",\"ACCEPT\",\"REJECT\",\"CONFIRMATION\",\"ROLLBACK\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
